2020-07-08 08:17:44,839 ERROR: Exception on /index [GET] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/main/routes.py", line 30, in index
    page, bp.config['POSTS_PER_PAGE'], False)
AttributeError: 'Blueprint' object has no attribute 'config'
2020-07-08 08:17:48,021 ERROR: Exception on /index [GET] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/main/routes.py", line 30, in index
    page, bp.config['POSTS_PER_PAGE'], False)
AttributeError: 'Blueprint' object has no attribute 'config'
2020-07-08 08:19:14,560 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:58]
2020-07-08 08:19:23,751 ERROR: Exception on /user/mark [GET] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/main/routes.py", line 66, in user
    return render_template('main/user.html', user=user, posts=posts.items,
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/templates/main/user.html", line 1, in top-level template code
    {% extends "main/base.html" %}
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/templates/main/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/templates/main/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/templates/main/user.html", line 15, in block "app_content"
    <p><a href="{{ url_for('main/edit_profile') }}">Edit your profile</a></p>
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main/edit_profile'. Did you mean 'main.edit_profile' instead?
2020-07-08 08:20:39,889 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:58]
2020-07-09 07:43:36,094 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:67]
