2020-07-08 06:32:37,367 ERROR: Exception on /reset_password_request [POST] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/routes.py", line 58, in reset_password_request
    send_password_reset_email(user)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/email.py", line 13, in send_password_reset_email
    html_body=render_template('email/reset_password.html',
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/templates/email/reset_password.html", line 9, in top-level template code
    <p>{{ url_for('reset_password', token=token, _external=True) }}</p>
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-07-08 06:35:24,010 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:55]
2020-07-08 06:35:32,316 ERROR: Exception on /reset_password_request [POST] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/routes.py", line 60, in reset_password_request
    return redirect(url_for('login'))
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2020-07-08 06:38:01,236 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:55]
2020-07-08 06:38:45,907 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTk0MjA1Mjg5LjIxMTI5NTF9.GIMO34EN3JYfbCCPkIEJ2bm2YfBnPj2aEOvnHQyKmXI [POST] [in /home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/github/projects/servers_and_webapps/microblog/application/auth/routes.py", line 77, in reset_password
    return redirect(url_for('login'))
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/mark/github/projects/servers_and_webapps/microblog/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2020-07-08 06:47:04,699 INFO: Microblog startup [in /home/mark/github/projects/servers_and_webapps/microblog/application/__init__.py:55]
